model_type: BetaCondInterpCaHyperpriorCharmModel
subnet:
  encoder:
    type: ElicInterpCaEncoder
    in_ch: 3
    out_ch: 320 # bottleneck_y
    main_ch: 192
    block_mid_ch: 96
    rate_level: 5
    ca_kwargs:
      actv: softplus
      use_interp: True
      use_bias: True
  decoder: 
    type: ElicInterpCaBetaCondDecoder
    ## beta cond settings
    L: 10
    max_beta: 5.12
    cond_ch: 512
    weight_init: True
    ## decoder settings
    in_ch: 320 # bottleneck_y
    out_ch: 3
    main_ch: 256
    block_mid_ch: 128
    pixel_shuffle: False
    use_tanh: False
    ## InterpCa settings
    rate_level: 5
    use_pi: False
    ca_kwargs:
      actv: softplus
      use_interp: True
      use_bias: True
  hyperencoder:
    type: Minnen20HyperEncoder
    bottleneck_y: 320
    bottleneck_z: 192
  hyperdecoder:
    type: Minnen20HyperDecoder
    bottleneck_z: 192
    hyper_out_ch: 640
  context_model:
    type: Minnen20CharmContextModel
    num_slices: 10
    hyper_out_ch: 640
    bottleneck_y: 320
    max_support_slices: 5
  entropy_model_z:
    type: SteEntropyBottleneck
    channels: 192 # bottleneck_z
  entropy_model_y:
    scale_bound: 0.11
    type: SteGaussianMeanScaleConditional
